#!/bin/bash

# Get Live Software Version And URL
URL=$(curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.33 (KHTML, like Gecko) Chrome/90.0.$RandNum.212 Safari/537.33" -s https://www.minecraft.net/en-us/download/server/ | grep server.jar | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*")
VERSION=$(curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.33 (KHTML, like Gecko) Chrome/90.0.$RandNum.212 Safari/537.33" -Ls https://www.minecraft.net/en-us/download/server | grep server.jar | grep -Eo "[0-9]+\.[0-9]+(\.[0-9]+)?")

# Write Details To Files
echo "${VERSION}" > VERSION
echo "${URL}" > URL
