#!/bin/bash

# Get Live Software Version And URL
URL=$(curl -s https://www.minecraft.net/en-us/download/server/ | grep server.jar | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*")
VERSION=$(curl -Ls https://www.minecraft.net/en-us/download/server | grep server.jar | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")

# Write Details To Files
echo "${VERSION}" > VERSION
echo "${URL}" > URL
